# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json .
# If package-lock.json exists, copy it
COPY package-lock.json* .
RUN npm install --production --ignore-scripts

# Copy source code
COPY . .

# Default command (not used by MCP start, but useful for local debugging)
CMD ["node", "main.js"]
